watch_stylesheet: true
watch_config: true
debug: false

komorebi:
  start_command: "komorebic start --whkd"
  stop_command: "komorebic stop --whkd"
  reload_command: "komorebic stop --whkd && komorebic start --whkd"

bars:
  status-bar:
    enabled: true
    screens: ['*'] 
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: false
    blur_effect:
      enabled: false 
      acrylic: false 
      dark_mode: false
      round_corners: false
      border_color: None
    window_flags:
      always_on_top: false
      windows_app_bar: true
    dimensions:
      width: "100%"
      height: 30
    padding:
      top: 3
      left: 3
      bottom: 3
      right: 3
    widgets:
      left:
        [
          "home",
          "taskbar",
        ]
      center: [
          "active_window"
        ]
      right:
        [
          "media",
          "weather",
          "volume",
          "clock",
          "power_menu"
        ]
widgets:
  media:
    type: "yasb.media.MediaWidget"
    options:
      label: "{title}{s}{artist}"
      label_alt: "{title}"
      separator: " - "
      hide_empty: true
      callbacks:
        on_left: "toggle_label"
        on_middle: "do_nothing"
        on_right: "do_nothing"
      max_field_size:
        label: 20
        label_alt: 30
      show_thumbnail: true
      controls_only: false
      controls_left: true
      controls_hide: false
      thumbnail_alpha: 80
      thumbnail_padding: 8
      thumbnail_corner_radius: 16
      icons:
        prev_track: "\ue892"
        next_track: "\ue893"
        play: "\ue768"
        pause: "\ue769"
      media_menu:
        blur: false
        round_corners: true
        round_corners_type: "normal"
        border_color: "system"
        alignment: "right"
        direction: "down"
        offset_top: 6
        offset_left: 0
        thumbnail_corner_radius: 8
        thumbnail_size: 120
        max_title_size: 60
        max_artist_size: 20
        show_source: true
      media_menu_icons:
        play: "\ue768"
        pause: "\ue769"
        prev_track: "\ue892"
        next_track: "\ue893"
      scrolling_label:
        enabled: false
        update_interval_ms: 33
        style: "left"  # can be "left", "right", "bounce", "bounce-ease"
        separator: " | "
        label_padding: 0
        always_scroll: false
        # Easing curve params: https://www.desmos.com/calculator/j7eamemxzi
        ease_slope: 20
        ease_pos: 0.8
        ease_min: 0.5
      label_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [ 1, 1 ]
  clock:
      type: "yasb.clock.ClockWidget"
      options:
        label: "<span>\uf4ab</span> {%H:%M}"
        label_alt: "<span>\uf4ab</span> {%A, %d %B %Y %H:%M}"
        timezones: [] #Looking up time zone info from registry
  komorebi_workspaces:
      type: "komorebi.workspaces.WorkspaceWidget"
      options:
          label_offline: "Komorebi Offline"
          label_workspace_btn: "\udb85\udcfc"
          label_workspace_active_btn: "\udb85\udcfb"
          label_default_name: "{index}"
          label_zero_index: false
          hide_empty_workspaces: false
          hide_if_offline: true
  komorebi_active_layout:
      type: "komorebi.active_layout.ActiveLayoutWidget"
      options:
        hide_if_offline: true
        label: "{icon}"
        layouts: ['bsp', 'columns', 'rows', 'grid', 'vertical_stack', 'horizontal_stack', 'ultrawide_vertical_stack','right_main_vertical_stack']
        layout_icons:
          bsp: "BSP"
          columns: "COLS"
          rows: "ROWS"
          grid: "GRID"
          vertical_stack: "V-STACK"
          horizontal_stack: "H-STACK"
          ultrawide_vertical_stack: "W-STACK"
          right_main_vertical_stack: "RMV-STACK"
          monocle: "MONOCLE"
          maximised: "MAX"
          floating: "FLOATING"
          paused: "PAUSED"
        callbacks:
          on_left: 'next_layout'
          on_middle: 'toggle_monocle'
          on_right: 'prev_layout'
  weather:
      type: "yasb.weather.WeatherWidget"
      options:
        label: "<span>{icon}</span> {temp}"
        label_alt: "{location}: Min {min_temp}, Max {max_temp}, Humidity {humidity}"
        api_key: '3bf4cf9a7c3f40d6b31174128242807'
        update_interval: 600 #Update interval in seconds, Min 600
        hide_decimal: true
        location: 'Ha Noi'
        callbacks:
          on_left: "toggle_label"
        icons: 
          sunnyDay: "\ue30d"
          clearNight: "\ue32b"
          cloudyDay: "\udb81\udd99"
          cloudyNight: "\ue311"
          rainyDay: "\udb81\ude7e"
          rainyNight: "\udb81\ude7e"
          snowyIcyDay: "\udb81\udd98"
          snowyIcyNight: "\udb81\udd98"
          blizzardDay: "\uebaa"
          default: "\uebaa"
          # https://www.weatherapi.com/docs/
          # Usage {temp}, {min_temp}, {max_temp}, {temp_f}, {min_temp_f}, {max_temp_f}, {location}, {humidity}, {icon}, {conditions}
  volume:
      type: "yasb.volume.VolumeWidget"
      options:
        label: "<span>{icon}</span> {level}"
        label_alt: "{volume}"
        volume_icons:
          - "\ueee8"  # Icon for muted
          - "\uf026"  # Icon for 0-10% volume
          - "\uf027"  # Icon for 11-30% volume
          - "\uf027"  # Icon for 31-60% volume
          - "\uf028"  # Icon for 61-100% volume
        callbacks:
          on_right: "exec cmd.exe /c start ms-settings:sound"
  power_menu:
      type: "yasb.power_menu.PowerMenuWidget"
      options:
        label: "\uf011"
        uptime: True
        blur: False
        blur_background: True
        animation_duration: 250 # Milisecond 
        button_row: 5 # Number of buttons in row, min 1 max 5
        buttons:
          signout: ["\udb80\udf43","Sign out"]
          shutdown: ["\uf011","Shut Down"]
          restart: ["\uead2","Restart"]
          hibernate: ["\uf28e","Hibernate"]
          cancel: ["\udb81\udf3a","Cancel"]
  custom_button:
      type: "yasb.custom.CustomWidget"
      options:
        label: "<span>\uf40e</span>"
        label_alt: "<span>\uf40e</span>"
        class_name: "start-menu"
        callbacks:
          on_left: "exec start_menu"
  active_window:
    type: "yasb.active_window.ActiveWindowWidget"
    options:
      label: "{win[title]}"
      label_alt: "[class_name='{win[class_name]}' exe='{win[process][name]}' hwnd={win[hwnd]}]"
      label_no_window: ""
      label_icon: true
      label_icon_size: 16
      max_length: 56
      max_length_ellipsis: "..."
      monitor_exclusive: true
      label_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [ 1, 1 ]
  taskbar:
    type: "yasb.taskbar.TaskbarWidget"
    options:
      icon_size: 16
      tooltip: true
      show_only_visible: false
      strict_filtering: true
      monitor_exclusive: false
      animation:
        enabled: true
      preview:
        enabled: false
        width: 240
        delay: 400
        padding: 8
        margin: 8
      title_label:
        enabled: false
        show: "always"
        min_length: 10
        max_length: 30
      ignore_apps:
        processes: []
        titles: []
        classes: []
  media_menu:
    blur: false                          # Whether to apply a blur effect to the popup background.
    round_corners: true                  # Whether to round the corners of the popup.
    round_corners_type: "normal"         # The type of corner rounding. Can be "normal" or "symmetric".
    border_color: "system"               # The border color of the popup. Can be a HEX, None or "system".
    alignment: "right"                   # The alignment of the popup relative to the widget. Can be "left", "center", or "right".
    direction: "down"                    # The direction in which the popup opens. Can be "up" or "down".
    offset_top: 6                        # The vertical offset of the popup from the widget.
    offset_left: 0                       # The horizontal offset of the popup from the widget.
    thumbnail_corner_radius: 8           # The corner radius for the thumbnail in the popup.
    thumbnail_size: 120                  # The size of the thumbnail in the popup.
    max_title_size: 60                   # The maximum size for the title in the popup.
    max_artist_size: 20                  # The maximum size for the artist name in the popup.
    show_source: true                    # Whether to show the media source (e.g., Spotify, YouTube) in the popup.
    show_volume_slider: false            # Whether to show the volume slider in the popup. Volume control per application.
  media_menu_icons:
    play: "\ue768"       # Icon for the play button in the popup.
    pause: "\ue769"      # Icon for the pause button in the popup.
    prev_track: "\ue892" # Icon for the previous track button in the popup.
    next_track: "\ue893" # Icon for the next track button in the popup.
    mute: "\ue994"       # Icon for the mute button in the popup.
    unmute: "\ue74f"     # Icon for the unmute button in the popup.
  scrolling_label:
    enabled: false                # Whether to enable the scrolling label.
    update_interval_ms: 33       # The update interval for the scrolling label in milliseconds.
    style: "left"                 # The style of the scrolling label. Can be "left", "right", "bounce", or "bounce-ease".
    separator: " | "              # The separator between repeating text in "left" or "right" scrolling style.
    label_padding: 1              # The padding around the label in "bounce" and "bounce-ease" style. By default it's one character on each side.
    ease_slope: 20                # The easing slope for the bounce effect. Easing curve params: https://www.desmos.com/calculator/j7eamemxzi
    ease_pos: 0.8                 # The easing curve position for the bounce effect.
    ease_min: 0.5                 # The minimum value for the bounce effect easing curve.
  home:
    type: "yasb.home.HomeWidget"
    options:
      label: "<span>\udb81\udf17</span>"
      menu_list:
      - { title: "User Home", path: "~" }
      - { title: "Download", path: "D:\\Downloads" }
      - { title: "Documents", path: "C:\\Users\\amn\\Documents" }
      - { title: "Pictures", path: "C:\\Users\\amn\\Pictures" }
      system_menu: true
      power_menu: true
      blur: true
      round_corners: true
      round_corners_type: "normal"
      border_color: "System"
      offset_top: 6
      offset_left: 0
      alignment: "left"
      direction: "down"
      menu_labels:
        shutdown: "Shutdown"
        restart: "Restart"
        hibernate: "Hibernate"
        logout: "Logout"
        lock: "Lock"
        sleep: "Sleep"
        system: "System Settings"
        about: "About This PC"
        task_manager: "Task Manager"
      label_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [ 1, 1 ]